[window]

opacity = 0.9

padding.x = 10
padding.y = 10

decorations = "Full"
decorations_theme_variant = "Light" # "Dark"

[font]

size = 10
normal.family = "Hack Nerd Font Mono"
bold.family = "Hack Nerd Font Mono"
italic.family = "Hack Nerd Font Mono"
bold_italic.family = "Hack Nerd Font Mono"

[colors.primary]
background = "#141412"
foreground = "#a0a8b7"

[colors.normal]
black   = "#0e1013"
red     = "#e55561"
green   = "#8ebd6b"
yellow  = "#e2b86b"
blue    = "#4fa6ed"
magenta = "#bf68d9"
cyan    = "#48b0bd"
white   = "#a0a8b7"

[colors.bright]
black   = "#0e1013"
red     = "#e55561"
green   = "#8ebd6b"
yellow  = "#e2b86b"
blue    = "#4fa6ed"
magenta = "#bf68d9"
cyan    = "#48b0bd"
white   = "#a0a8b7"
